# data.table library in R Programming for Data Analysis

In [ ]:
#Importing the data.table library

library(data.table)

In [ ]:
#url = "Paste Url link"
#df = fread(url)
df <- fread('cars_datasets.csv')

In [3]:
# Type/Class of the df object

class(df)

[1] "data.table" "data.frame"

In [4]:
# Column names

names(df)

 [1] "V1"           "price"        "brand"        "model"        "year"
 [6] "title_status" "mileage"      "color"        "vin"          "lot"
[11] "state"        "country"      "condition"

In [8]:
# Show first few rows

head(df)
#head(df,3)
#head(df$model)

  V1 price brand     model   year title_status  mileage color
1 0   6300 toyota    cruiser 2008 clean vehicle 274117  black
2 1   2899 ford      se      2011 clean vehicle 190552  silver
3 2   5350 dodge     mpv     2018 clean vehicle  39590  silver
4 3  25000 ford      door    2014 clean vehicle  64146  blue
5 4  27700 chevrolet 1500    2018 clean vehicle   6654  red
6 5   5700 dodge     mpv     2018 clean vehicle  45561  white
  vin               lot       state      country condition
1 jtezu11f88k007763 159348797 new jersey usa     10 days left
2 2fmdk3gc4bbb02217 166951262 tennessee  usa     6 days left
3 3c4pdcgg5jt346413 167655728 georgia    usa     2 days left
4 1ftfw1et4efc23745 167753855 virginia   usa     22 hours left
5 3gcpcrec2jg473991 167763266 florida    usa     22 hours left
6 2c4rdgeg9jr237989 167655771 texas      usa     2 days left

In [12]:
# Show last few rows

tail(df)
#tail(df,3)
#tail(df$color,4)

  V1   price brand  model year title_status  mileage color  vin
1 2493 9200  nissan versa 2018 clean vehicle 33027   black  3n1cn7ap0jl883768
2 2494 7800  nissan versa 2019 clean vehicle 23609   red    3n1cn7ap9kl880319
3 2495 9200  nissan versa 2018 clean vehicle 34553   silver 3n1cn7ap5jl884088
4 2496 9200  nissan versa 2018 clean vehicle 31594   silver 3n1cn7ap9jl884191
5 2497 9200  nissan versa 2018 clean vehicle 32557   black  3n1cn7ap3jl883263
6 2498 9200  nissan versa 2018 clean vehicle 31371   silver 3n1cn7ap4jl884311
  lot       state      country condition
1 167762224 florida    usa     21 hours left
2 167722715 california usa     1 days left
3 167762225 florida    usa     21 hours left
4 167762226 florida    usa     21 hours left
5 167762227 florida    usa     2 days left
6 167762228 florida    usa     21 hours left

In [13]:
# Data type of each column

str(df)

Classes 'data.table' and 'data.frame':	2499 obs. of  13 variables:
 $ V1          : int  0 1 2 3 4 5 6 7 8 9 ...
 $ price       : int  6300 2899 5350 25000 27700 5700 7300 13350 14600 5250 ...
 $ brand       : chr  "toyota" "ford" "dodge" "ford" ...
 $ model       : chr  "cruiser" "se" "mpv" "door" ...
 $ year        : int  2008 2011 2018 2014 2018 2018 2010 2017 2018 2017 ...
 $ title_status: chr  "clean vehicle" "clean vehicle" "clean vehicle" "clean vehicle" ...
 $ mileage     : num  274117 190552 39590 64146 6654 ...
 $ color       : chr  "black" "silver" "silver" "blue" ...
 $ vin         : chr  "jtezu11f88k007763" "2fmdk3gc4bbb02217" "3c4pdcgg5jt346413" "1ftfw1et4efc23745" ...
 $ lot         : int  159348797 166951262 167655728 167753855 167763266 167655771 167753872 167692494 167763267 167656121 ...
 $ state       : chr  "new jersey" "tennessee" "georgia" "virginia" ...
 $ country     : chr  "usa" "usa" "usa" "usa" ...
 $ condition   : chr  "10 days left" "6 days left" "2 days left" "22 hours left" ...
 - attr(*, ".internal.selfref")=<externalptr>

In [14]:
# Return number of columns and rows of dataframe

dim(df)

[1] 2499   13

In [15]:
#  Number of rows

nrow(df)

[1] 2499

In [16]:
#  Number of columns

ncol(df)

[1] 13

In [17]:
#Basic Summary

summary(df)

       V1             price          brand              model
 Min.   :   0.0   Min.   :    0   Length:2499        Length:2499
 1st Qu.: 624.5   1st Qu.:10200   Class :character   Class :character
 Median :1249.0   Median :16900   Mode  :character   Mode  :character
 Mean   :1249.0   Mean   :18768
 3rd Qu.:1873.5   3rd Qu.:25556
 Max.   :2498.0   Max.   :84900
      year      title_status          mileage           color
 Min.   :1973   Length:2499        Min.   :      0   Length:2499
 1st Qu.:2016   Class :character   1st Qu.:  21467   Class :character
 Median :2018   Mode  :character   Median :  35365   Mode  :character
 Mean   :2017                      Mean   :  52299
 3rd Qu.:2019                      3rd Qu.:  63473
 Max.   :2020                      Max.   :1017936
     vin                 lot               state             country
 Length:2499        Min.   :159348797   Length:2499        Length:2499
 Class :character   1st Qu.:167625331   Class :character   Class :character
 Mode  :character   Median :167745058   Mode  :character   Mode  :character
                    Mean   :167691389
                    3rd Qu.:167779772
                    Max.   :167805500
  condition
 Length:2499
 Class :character
 Mode  :character

In [19]:
# Extract first few rows and columns

#df[1:4]
df[1:4,1:3]

  V1 price brand
1 0   6300 toyota
2 1   2899 ford
3 2   5350 dodge
4 3  25000 ford

In [20]:
# Filter for year = 2018

df[year == 2018]

    V1   price brand     model      year title_status  mileage color
1     2   5350 dodge     mpv        2018 clean vehicle 39590   silver
2     4  27700 chevrolet 1500       2018 clean vehicle  6654   red
3     5   5700 dodge     mpv        2018 clean vehicle 45561   white
4     8  14600 chevrolet malibu     2018 clean vehicle  9371   silver
5    12  31900 chevrolet 1500       2018 clean vehicle 22909   black
6    16   5200 kia       forte      2018 clean vehicle 46194   blue
7    17  16500 buick     encore     2018 clean vehicle 20002   red
8    21   7300 kia       forte      2018 clean vehicle 38823   black
9    37  19200 chevrolet 1500       2018 clean vehicle  2430   white
10   42  30500 chevrolet 1500       2018 clean vehicle 30442   red
11  100  13600 ford      focus      2018 clean vehicle 16971   black
12  103  13800 ford      focus      2018 clean vehicle 23164   white
13  106   8700 ford      focus      2018 clean vehicle 21405   white
14  109  23100 dodge     durango    2018 clean vehicle 49496   white
15  112  17000 ford      escape     2018 clean vehicle 34819   gold
16  115  25000 dodge     charger    2018 clean vehicle 28307   silver
17  127  53000 chevrolet 3500       2018 clean vehicle 16105   black
18  131   4160 dodge     mpv        2018 clean vehicle 32870   gray
19  133   5690 dodge     mpv        2018 clean vehicle 47085   silver
20  136   5090 dodge     mpv        2018 clean vehicle 42989   gray
21  140   4260 dodge     mpv        2018 clean vehicle 33957   gray
22  143   7210 dodge     doors      2018 clean vehicle 38910   black
23  146   6800 dodge     doors      2018 clean vehicle 36767   gray
24  148  10780 dodge     mpv        2018 clean vehicle 19420   white
25  151   6440 chrysler  doors      2018 clean vehicle 20942   gray
26  154   4040 dodge     mpv        2018 clean vehicle 50765   red
27  157   4290 dodge     mpv        2018 clean vehicle 39029   white
28  160   4160 dodge     mpv        2018 clean vehicle  6743   gray
29  163   6060 dodge     doors      2018 clean vehicle 32504   black
30  166   6140 dodge     doors      2018 clean vehicle 52966   silver
... ...  ...   ...       ...        ...  ...           ...     ...
366 2456 16500 nissan    pathfinder 2018 clean vehicle 34841   black
367 2457 13900 nissan    rogue      2018 clean vehicle 35065   gray
368 2458 12400 nissan    altima     2018 clean vehicle 37741   black
369 2459 13000 nissan    altima     2018 clean vehicle 27488   gray
370 2460 16500 nissan    pathfinder 2018 clean vehicle 37452   gray
371 2461 13900 nissan    rogue      2018 clean vehicle 39797   black
372 2462 16500 nissan    pathfinder 2018 clean vehicle 36714   black
373 2463 13900 nissan    rogue      2018 clean vehicle 36207   black
374 2464 13900 nissan    rogue      2018 clean vehicle 38563   black
375 2465 13900 nissan    rogue      2018 clean vehicle 39885   silver
376 2466 12100 nissan    altima     2018 clean vehicle 41852   silver
377 2467 16500 nissan    pathfinder 2018 clean vehicle 39454   silver
378 2468 16500 nissan    pathfinder 2018 clean vehicle 40203   blue
379 2469 13900 nissan    rogue      2018 clean vehicle 34547   white
380 2472  9200 nissan    versa      2018 clean vehicle 33808   black
381 2474  9200 nissan    versa      2018 clean vehicle 33931   black
382 2476 13900 nissan    rogue      2018 clean vehicle 44313   white
383 2477  9100 nissan    versa      2018 clean vehicle 33078   black
384 2479 13900 nissan    rogue      2018 clean vehicle 42502   black
385 2481  9200 nissan    versa      2018 clean vehicle 39577   silver
386 2483  9200 nissan    versa      2018 clean vehicle 41220   black
387 2485 13900 nissan    rogue      2018 clean vehicle 41539   black
388 2487 13900 nissan    rogue      2018 clean vehicle 39924   white
389 2489 13900 nissan    rogue      2018 clean vehicle 40259   gray
390 2491  9200 nissan    versa      2018 clean vehicle 35677   black
391 2493  9200 nissan    versa      2018 clean vehicle 33027   black
392 2495  9200 nissan    versa      2018 clean vehicle 34553   silver
393 2496  9200 nissan    versa      2018 clean vehicle 31594   silver
394 2497  9200 nissan    versa      2018 clean vehicle 32557   black
395 2498  9200 nissan    versa      2018 clean vehicle 31371   silver
    vin               lot       state          country condition
1   3c4pdcgg5jt346413 167655728 georgia        usa     2 days left
2   3gcpcrec2jg473991 167763266 florida        usa     22 hours left
3   2c4rdgeg9jr237989 167655771 texas          usa     2 days left
4   1g1zd5st5jf191860 167763267 florida        usa     22 hours left
5   3gcukrec0jg176059 167763273 tennessee      usa     22 hours left
6   3kpfk4a77je198723 167801757 north carolina usa     2 days left
7   kl4cj1sb6jb688844 167763275 tennessee      usa     22 hours left
8   3kpfl4a79je272611 167801773 north carolina usa     2 days left
9   1gcncneh5jz302471 167763391 tennessee      usa     22 hours left
10  3gcukrec4jg204915 167763393 tennessee      usa     22 hours left
11  1fadp3m26jl307477 167755490 south carolina usa     21 hours left
12  1fadp3j2xjl279400 167755491 south carolina usa     21 hours left
13  1fadp3k23jl219764 167755494 south carolina usa     21 hours left
14  1c4rdjdg2jc329601 167755496 south carolina usa     21 hours left
15  1fmcu9hd6juc54783 167755501 south carolina usa     21 hours left
16  2c3cdxjg6jh224431 167755814 michigan       usa     21 hours left
17  1gc4k1ey0jf149152 167765123 washington     usa     21 hours left
18  3c4pdcab8jt166940 167656464 florida        usa     17 hours left
19  2c4rdgeg8jr337145 167656466 florida        usa     17 hours left
20  2c4rdgcg2jr218218 167656467 florida        usa     17 hours left
21  3c4pdcabxjt311007 167656471 florida        usa     16 hours left
22  2c3cdxct1jh233225 167656472 florida        usa     16 hours left
23  2c3cdxhgxjh125388 167656473 florida        usa     16 hours left
24  1c4sdjct1jc174166 167656474 florida        usa     16 hours left
25  2c3ccakg8jh168457 167656475 florida        usa     17 hours left
26  3c4pdcab6jt273002 167656476 florida        usa     16 hours left
27  3c4pdcab0jt474412 167656477 florida        usa     16 hours left
28  3c4pdcab8jt384019 167656478 florida        usa     16 hours left
29  3c4pddgg1jt523058 167656479 florida        usa     18 hours left
30  2c3cdxbg0jh187083 167656480 florida        usa     16 hours left
... ...               ...       ...            ...     ...
366 5n1dr2mm0jc631567 167762103 florida        usa     2 days left
367 5n1at2mt8jc761351 167762104 florida        usa     2 days left
368 1n4al3apxjc193322 167762105 florida        usa     21 hours left
369 1n4al3ap4jc153320 167762106 florida        usa     21 hours left
370 5n1dr2mm2jc632610 167762107 florida        usa     21 hours left
371 knmat2mt2jp581604 167762108 florida        usa     21 hours left
372 5n1dr2mm8jc627265 167762109 florida        usa     21 hours left
373 5n1at2mt3jc761242 167762110 florida        usa     21 hours left
374 knmat2mt4jp581457 167762111 florida        usa     21 hours left
375 5n1at2mt4jc764747 167762112 florida        usa     21 hours left
376 1n4al3apxjc159820 167762113 florida        usa     21 hours left
377 5n1dr2mm6jc650009 167762116 florida        usa     21 hours left
378 5n1dr2mm3jc657841 167762117 florida        usa     21 hours left
379 knmat2mtxjp581687 167762118 florida        usa     21 hours left
380 3n1cn7ap3jl883781 167762207 florida        usa     2 days left
381 3n1cn7ap5jl882616 167762208 florida        usa     2 days left
382 knmat2mt8jp581980 167762209 florida        usa     21 hours left
383 3n1cn7ap0jl882846 167762210 florida        usa     21 hours left
384 knmat2mt3jp582048 167762211 florida        usa     21 hours left
385 3n1cn7ap7jl883833 167762212 florida        usa     2 days left
386 3n1cn7ap6jl883130 167762213 florida        usa     21 hours left
387 knmat2mt4jp581250 167762214 florida        usa     21 hours left
388 knmat2mt6jp582092 167762218 florida        usa     21 hours left
389 knmat2mt9jp582734 167762219 florida        usa     21 hours left
390 3n1cn7ap7jl882312 167762221 florida        usa     21 hours left
391 3n1cn7ap0jl883768 167762224 florida        usa     21 hours left
392 3n1cn7ap5jl884088 167762225 florida        usa     21 hours left
393 3n1cn7ap9jl884191 167762226 florida        usa     21 hours left
394 3n1cn7ap3jl883263 167762227 florida        usa     2 days left
395 3n1cn7ap4jl884311 167762228 florida        usa     21 hours left

In [21]:
#Filter for year = 2018 & color = gray
df[year == "2018" & color == "gray"]

    V1   price brand     model      year title_status  mileage color
1    131  4160 dodge     mpv        2018 clean vehicle 32870   gray
2    136  5090 dodge     mpv        2018 clean vehicle 42989   gray
3    140  4260 dodge     mpv        2018 clean vehicle 33957   gray
4    146  6800 dodge     doors      2018 clean vehicle 36767   gray
5    151  6440 chrysler  doors      2018 clean vehicle 20942   gray
6    160  4160 dodge     mpv        2018 clean vehicle  6743   gray
7    204  6000 chevrolet malibu     2018 clean vehicle 42090   gray
8    325  4050 heartland pioneer    2018 clean vehicle     1   gray
9    427  2630 nissan    doors      2018 clean vehicle 36739   gray
10   464  3390 nissan    doors      2018 clean vehicle 38349   gray
11   471 21400 gmc       acadia     2018 clean vehicle 54332   gray
12   489  8350 nissan    cab        2018 clean vehicle 32256   gray
13   685 32800 chevrolet tahoe      2018 clean vehicle 46915   gray
14   687 19600 chevrolet 1500       2018 clean vehicle 41672   gray
15   691 13000 chevrolet malibu     2018 clean vehicle 41751   gray
16   745 29800 chevrolet suburban   2018 clean vehicle 48807   gray
17   779 26300 chevrolet camaro     2018 clean vehicle 11150   gray
18   809 22500 dodge     charger    2018 clean vehicle 26026   gray
19   825 14300 dodge     journey    2018 clean vehicle 19164   gray
20   843 18700 dodge     challenger 2018 clean vehicle 36358   gray
21   858 23000 dodge     charger    2018 clean vehicle 26996   gray
22   860 21500 dodge     challenger 2018 clean vehicle  6748   gray
23   895 17000 dodge     caravan    2018 clean vehicle 36299   gray
24   904 18500 dodge     challenger 2018 clean vehicle 34272   gray
25   936 13300 dodge     caravan    2018 clean vehicle 48681   gray
26  1119 21000 dodge     charger    2018 clean vehicle 12554   gray
27  1259 24300 ford      f-150      2018 clean vehicle  6290   gray
28  1262 39000 ford      f-150      2018 clean vehicle 25839   gray
29  1263 13900 ford      escape     2018 clean vehicle 60715   gray
30  1372 36000 ford      max        2018 clean vehicle 58576   gray
... ...  ...   ...       ...        ...  ...           ...     ...
45  2155 26000 ford      f-150      2018 clean vehicle 33350   gray
46  2167 21500 ford      f-150      2018 clean vehicle 43519   gray
47  2212 11450 nissan    sport      2018 clean vehicle 35831   gray
48  2213 11050 nissan    sport      2018 clean vehicle 35050   gray
49  2214 11400 nissan    sport      2018 clean vehicle 34924   gray
50  2216 10850 nissan    sport      2018 clean vehicle 39985   gray
51  2219 10800 nissan    sport      2018 clean vehicle 40455   gray
52  2222 10850 nissan    sport      2018 clean vehicle 39183   gray
53  2228 10800 nissan    sport      2018 clean vehicle 40332   gray
54  2256   750 nissan    sentra     2018 clean vehicle 37088   gray
55  2259  8300 nissan    sedan      2018 clean vehicle 43064   gray
56  2260  8300 nissan    sedan      2018 clean vehicle 47510   gray
57  2261  8000 nissan    sedan      2018 clean vehicle 52571   gray
58  2285 12500 nissan    sport      2018 clean vehicle 43187   gray
59  2287  8000 nissan    versa      2018 clean vehicle 53903   gray
60  2324 28000 nissan    armada     2018 clean vehicle 29554   gray
61  2328 17000 nissan    altima     2018 clean vehicle 44423   gray
62  2396 13300 nissan    sport      2018 clean vehicle 39247   gray
63  2399 10300 nissan    sentra     2018 clean vehicle 41203   gray
64  2401 24000 nissan    murano     2018 clean vehicle 31551   gray
65  2402 10400 nissan    sentra     2018 clean vehicle 38761   gray
66  2403 10200 nissan    sentra     2018 clean vehicle 42838   gray
67  2431 14300 nissan    sport      2018 clean vehicle 44864   gray
68  2433 11900 nissan    sentra     2018 clean vehicle 16778   gray
69  2447 12500 nissan    altima     2018 clean vehicle 34460   gray
70  2452 13900 nissan    rogue      2018 clean vehicle 37073   gray
71  2457 13900 nissan    rogue      2018 clean vehicle 35065   gray
72  2459 13000 nissan    altima     2018 clean vehicle 27488   gray
73  2460 16500 nissan    pathfinder 2018 clean vehicle 37452   gray
74  2489 13900 nissan    rogue      2018 clean vehicle 40259   gray
    vin               lot       state          country condition
1   3c4pdcab8jt166940 167656464 florida        usa     17 hours left
2   2c4rdgcg2jr218218 167656467 florida        usa     17 hours left
3   3c4pdcabxjt311007 167656471 florida        usa     16 hours left
4   2c3cdxhgxjh125388 167656473 florida        usa     16 hours left
5   2c3ccakg8jh168457 167656475 florida        usa     17 hours left
6   3c4pdcab8jt384019 167656478 florida        usa     16 hours left
7   1g1zb5st8jf226848 167765944 texas          usa     21 hours left
8   5sfpb3326je365727 167265963 pennsylvania   usa     7 days left
9   3n1cn7ap5jl872135 167692446 california     usa     20 hours left
10  3n1ab7ap5jy293102 167692449 california     usa     20 hours left
11  1gkknwls6jz133440 167602130 new jersey     usa     2 hours left
12  1n6aa1ej3jn519666 167692453 california     usa     20 hours left
13  1gnskbkc9jr370082 167787953 oklahoma       usa     21 hours left
14  1gcvkreh7jz295386 167787956 oklahoma       usa     21 hours left
15  1g1zd5st8jf242655 167787968 oklahoma       usa     21 hours left
16  1gnschkc1jr387653 167798092 nevada         usa     2 days left
17  1g1fb1rx5j0103693 167801223 kansas         usa     2 days left
18  2c3cdxjg4jh292503 167766491 wisconsin      usa     4 days left
19  3c4pdcab2jt216649 167717039 north carolina usa     21 hours left
20  2c3cdzag5jh245542 167773134 new jersey     usa     Listing Expired
21  2c3cdxjg7jh189253 167735435 michigan       usa     21 hours left
22  2c3cdzag8jh321934 167778953 wisconsin      usa     2 days left
23  2c4rdgeg5jr147562 167781292 new jersey     usa     2 days left
24  2c3cdzag4jh302832 167782327 california     usa     2 days left
25  2c4rdgegxjr331914 167555075 california     usa     8 days left
26  2c3cdxbg4jh164292 167639649 texas          usa     10 days left
27  1ftex1cp1jkf40656 167722443 illinois       usa     21 hours left
28  1ftfw1e53jfd63829 167778962 illinois       usa     2 days left
29  1fmcu0hdxjuc12967 167778964 wisconsin      usa     21 hours left
30  1fmjk1jt1jea23803 167472824 wisconsin      usa     22 hours left
... ...               ...       ...            ...     ...
45  1ftfw1e58jfa37766 167749256 pennsylvania   usa     3 days left
46  1ftfw1e55jfc57253 167749265 pennsylvania   usa     3 days left
47  jn1bj1cp5jw161563 167456254 florida        usa     7 days left
48  jn1bj1cp3jw108442 167456255 florida        usa     7 days left
49  jn1bj1cp1jw161494 167456258 florida        usa     7 days left
50  jn1bj1cp8jw161668 167456317 florida        usa     7 days left
51  jn1bj1cp7jw108055 167456334 florida        usa     7 days left
52  jn1bj1cp2jw108545 167456338 florida        usa     7 days left
53  jn1bj1cp9jw108428 167456351 florida        usa     7 days left
54  3n1ab7ap3jy312956 167494347 missouri       usa     8 days left
55  3n1cn7apxjl833105 167519152 california     usa     7 days left
56  3n1cn7ap7jl819100 167519154 california     usa     7 days left
57  3n1cn7ap9jl817056 167519159 california     usa     7 days left
58  jn1bj1cr5jw281199 167724477 california     usa     2 days left
59  3n1cn7ap8jl818263 167724479 california     usa     2 days left
60  jn8ay2nc4j9558303 167750230 pennsylvania   usa     3 days left
61  1n4al3ap1jc191541 167750844 texas          usa     21 hours left
62  jn1bj1cr7jw262489 167615917 minnesota      usa     14 hours left
63  3n1ab7ap7jy307016 167615924 minnesota      usa     14 hours left
64  5n1az2mhxjn157718 167615931 minnesota      usa     14 hours left
65  3n1ab7ap0jy322490 167615932 minnesota      usa     14 hours left
66  3n1ab7ap3jy324878 167615934 minnesota      usa     14 hours left
67  jn1bj1cr3jw263168 167760154 ohio           usa     21 hours left
68  3n1ab7ap8jl635929 167760156 ohio           usa     21 hours left
69  1n4al3ap1jc193208 167762095 florida        usa     2 days left
70  knmat2mt6jp582724 167762100 florida        usa     21 hours left
71  5n1at2mt8jc761351 167762104 florida        usa     2 days left
72  1n4al3ap4jc153320 167762106 florida        usa     21 hours left
73  5n1dr2mm2jc632610 167762107 florida        usa     21 hours left
74  knmat2mt9jp582734 167762219 florida        usa     21 hours left

In [23]:
# Filter for cars with year = 2018 OR color = black
z <- df[year== "2018" | color == "Black"]

z

    V1   price brand     model      year title_status  mileage color
1     2   5350 dodge     mpv        2018 clean vehicle 39590   silver
2     4  27700 chevrolet 1500       2018 clean vehicle  6654   red
3     5   5700 dodge     mpv        2018 clean vehicle 45561   white
4     8  14600 chevrolet malibu     2018 clean vehicle  9371   silver
5    12  31900 chevrolet 1500       2018 clean vehicle 22909   black
6    16   5200 kia       forte      2018 clean vehicle 46194   blue
7    17  16500 buick     encore     2018 clean vehicle 20002   red
8    21   7300 kia       forte      2018 clean vehicle 38823   black
9    37  19200 chevrolet 1500       2018 clean vehicle  2430   white
10   42  30500 chevrolet 1500       2018 clean vehicle 30442   red
11  100  13600 ford      focus      2018 clean vehicle 16971   black
12  103  13800 ford      focus      2018 clean vehicle 23164   white
13  106   8700 ford      focus      2018 clean vehicle 21405   white
14  109  23100 dodge     durango    2018 clean vehicle 49496   white
15  112  17000 ford      escape     2018 clean vehicle 34819   gold
16  115  25000 dodge     charger    2018 clean vehicle 28307   silver
17  127  53000 chevrolet 3500       2018 clean vehicle 16105   black
18  131   4160 dodge     mpv        2018 clean vehicle 32870   gray
19  133   5690 dodge     mpv        2018 clean vehicle 47085   silver
20  136   5090 dodge     mpv        2018 clean vehicle 42989   gray
21  140   4260 dodge     mpv        2018 clean vehicle 33957   gray
22  143   7210 dodge     doors      2018 clean vehicle 38910   black
23  146   6800 dodge     doors      2018 clean vehicle 36767   gray
24  148  10780 dodge     mpv        2018 clean vehicle 19420   white
25  151   6440 chrysler  doors      2018 clean vehicle 20942   gray
26  154   4040 dodge     mpv        2018 clean vehicle 50765   red
27  157   4290 dodge     mpv        2018 clean vehicle 39029   white
28  160   4160 dodge     mpv        2018 clean vehicle  6743   gray
29  163   6060 dodge     doors      2018 clean vehicle 32504   black
30  166   6140 dodge     doors      2018 clean vehicle 52966   silver
... ...  ...   ...       ...        ...  ...           ...     ...
366 2456 16500 nissan    pathfinder 2018 clean vehicle 34841   black
367 2457 13900 nissan    rogue      2018 clean vehicle 35065   gray
368 2458 12400 nissan    altima     2018 clean vehicle 37741   black
369 2459 13000 nissan    altima     2018 clean vehicle 27488   gray
370 2460 16500 nissan    pathfinder 2018 clean vehicle 37452   gray
371 2461 13900 nissan    rogue      2018 clean vehicle 39797   black
372 2462 16500 nissan    pathfinder 2018 clean vehicle 36714   black
373 2463 13900 nissan    rogue      2018 clean vehicle 36207   black
374 2464 13900 nissan    rogue      2018 clean vehicle 38563   black
375 2465 13900 nissan    rogue      2018 clean vehicle 39885   silver
376 2466 12100 nissan    altima     2018 clean vehicle 41852   silver
377 2467 16500 nissan    pathfinder 2018 clean vehicle 39454   silver
378 2468 16500 nissan    pathfinder 2018 clean vehicle 40203   blue
379 2469 13900 nissan    rogue      2018 clean vehicle 34547   white
380 2472  9200 nissan    versa      2018 clean vehicle 33808   black
381 2474  9200 nissan    versa      2018 clean vehicle 33931   black
382 2476 13900 nissan    rogue      2018 clean vehicle 44313   white
383 2477  9100 nissan    versa      2018 clean vehicle 33078   black
384 2479 13900 nissan    rogue      2018 clean vehicle 42502   black
385 2481  9200 nissan    versa      2018 clean vehicle 39577   silver
386 2483  9200 nissan    versa      2018 clean vehicle 41220   black
387 2485 13900 nissan    rogue      2018 clean vehicle 41539   black
388 2487 13900 nissan    rogue      2018 clean vehicle 39924   white
389 2489 13900 nissan    rogue      2018 clean vehicle 40259   gray
390 2491  9200 nissan    versa      2018 clean vehicle 35677   black
391 2493  9200 nissan    versa      2018 clean vehicle 33027   black
392 2495  9200 nissan    versa      2018 clean vehicle 34553   silver
393 2496  9200 nissan    versa      2018 clean vehicle 31594   silver
394 2497  9200 nissan    versa      2018 clean vehicle 32557   black
395 2498  9200 nissan    versa      2018 clean vehicle 31371   silver
    vin               lot       state          country condition
1   3c4pdcgg5jt346413 167655728 georgia        usa     2 days left
2   3gcpcrec2jg473991 167763266 florida        usa     22 hours left
3   2c4rdgeg9jr237989 167655771 texas          usa     2 days left
4   1g1zd5st5jf191860 167763267 florida        usa     22 hours left
5   3gcukrec0jg176059 167763273 tennessee      usa     22 hours left
6   3kpfk4a77je198723 167801757 north carolina usa     2 days left
7   kl4cj1sb6jb688844 167763275 tennessee      usa     22 hours left
8   3kpfl4a79je272611 167801773 north carolina usa     2 days left
9   1gcncneh5jz302471 167763391 tennessee      usa     22 hours left
10  3gcukrec4jg204915 167763393 tennessee      usa     22 hours left
11  1fadp3m26jl307477 167755490 south carolina usa     21 hours left
12  1fadp3j2xjl279400 167755491 south carolina usa     21 hours left
13  1fadp3k23jl219764 167755494 south carolina usa     21 hours left
14  1c4rdjdg2jc329601 167755496 south carolina usa     21 hours left
15  1fmcu9hd6juc54783 167755501 south carolina usa     21 hours left
16  2c3cdxjg6jh224431 167755814 michigan       usa     21 hours left
17  1gc4k1ey0jf149152 167765123 washington     usa     21 hours left
18  3c4pdcab8jt166940 167656464 florida        usa     17 hours left
19  2c4rdgeg8jr337145 167656466 florida        usa     17 hours left
20  2c4rdgcg2jr218218 167656467 florida        usa     17 hours left
21  3c4pdcabxjt311007 167656471 florida        usa     16 hours left
22  2c3cdxct1jh233225 167656472 florida        usa     16 hours left
23  2c3cdxhgxjh125388 167656473 florida        usa     16 hours left
24  1c4sdjct1jc174166 167656474 florida        usa     16 hours left
25  2c3ccakg8jh168457 167656475 florida        usa     17 hours left
26  3c4pdcab6jt273002 167656476 florida        usa     16 hours left
27  3c4pdcab0jt474412 167656477 florida        usa     16 hours left
28  3c4pdcab8jt384019 167656478 florida        usa     16 hours left
29  3c4pddgg1jt523058 167656479 florida        usa     18 hours left
30  2c3cdxbg0jh187083 167656480 florida        usa     16 hours left
... ...               ...       ...            ...     ...
366 5n1dr2mm0jc631567 167762103 florida        usa     2 days left
367 5n1at2mt8jc761351 167762104 florida        usa     2 days left
368 1n4al3apxjc193322 167762105 florida        usa     21 hours left
369 1n4al3ap4jc153320 167762106 florida        usa     21 hours left
370 5n1dr2mm2jc632610 167762107 florida        usa     21 hours left
371 knmat2mt2jp581604 167762108 florida        usa     21 hours left
372 5n1dr2mm8jc627265 167762109 florida        usa     21 hours left
373 5n1at2mt3jc761242 167762110 florida        usa     21 hours left
374 knmat2mt4jp581457 167762111 florida        usa     21 hours left
375 5n1at2mt4jc764747 167762112 florida        usa     21 hours left
376 1n4al3apxjc159820 167762113 florida        usa     21 hours left
377 5n1dr2mm6jc650009 167762116 florida        usa     21 hours left
378 5n1dr2mm3jc657841 167762117 florida        usa     21 hours left
379 knmat2mtxjp581687 167762118 florida        usa     21 hours left
380 3n1cn7ap3jl883781 167762207 florida        usa     2 days left
381 3n1cn7ap5jl882616 167762208 florida        usa     2 days left
382 knmat2mt8jp581980 167762209 florida        usa     21 hours left
383 3n1cn7ap0jl882846 167762210 florida        usa     21 hours left
384 knmat2mt3jp582048 167762211 florida        usa     21 hours left
385 3n1cn7ap7jl883833 167762212 florida        usa     2 days left
386 3n1cn7ap6jl883130 167762213 florida        usa     21 hours left
387 knmat2mt4jp581250 167762214 florida        usa     21 hours left
388 knmat2mt6jp582092 167762218 florida        usa     21 hours left
389 knmat2mt9jp582734 167762219 florida        usa     21 hours left
390 3n1cn7ap7jl882312 167762221 florida        usa     21 hours left
391 3n1cn7ap0jl883768 167762224 florida        usa     21 hours left
392 3n1cn7ap5jl884088 167762225 florida        usa     21 hours left
393 3n1cn7ap9jl884191 167762226 florida        usa     21 hours left
394 3n1cn7ap3jl883263 167762227 florida        usa     2 days left
395 3n1cn7ap4jl884311 167762228 florida        usa     21 hours left

In [24]:
#Filter for brand in kia ,dodge
z <- df[brand %in% c('kia','dodge')]

head(z)

# OR

#setkey(df, brand)

#z = df[c("dodge","kia")]
#head(z)

  V1 price brand model   year title_status  mileage color  vin
1  2  5350 dodge mpv     2018 clean vehicle  39590  silver 3c4pdcgg5jt346413
2  5  5700 dodge mpv     2018 clean vehicle  45561  white  2c4rdgeg9jr237989
3 10 10400 dodge coupe   2009 clean vehicle 107856  orange 2b3lj54t49h509675
4 16  5200 kia   forte   2018 clean vehicle  46194  blue   3kpfk4a77je198723
5 21  7300 kia   forte   2018 clean vehicle  38823  black  3kpfl4a79je272611
6 26 21500 kia   sorento 2020 clean vehicle  11451  blue   5xypg4a59lg616029
  lot       state          country condition
1 167655728 georgia        usa     2 days left
2 167655771 texas          usa     2 days left
3 167753874 georgia        usa     22 hours left
4 167801757 north carolina usa     2 days left
5 167801773 north carolina usa     2 days left
6 167801828 north carolina usa     2 days left

In [26]:
# Select single coloum

#z <- df[,.(state)]
#head(z)

#OR in row manner
z <- df$state
head(z)

[1] "new jersey" "tennessee"  "georgia"    "virginia"   "florida"
[6] "texas"

In [27]:
# Select more than one columns

z <- df[,.(model,state)]
head(z,4)

  model   state
1 cruiser new jersey
2 se      tennessee
3 mpv     georgia
4 door    virginia

In [28]:
# Unique car production years

df[,unique(year)]

 [1] 2008 2011 2018 2014 2010 2017 2009 2013 2015 2020 2016 1973 2003 2019 2002
[16] 2000 2001 2005 2012 2006 2007 1998 2004 1994 1997 1996 1999 1984 1995 1993

In [29]:
# Maximum of the "mileage" column

df[,max(mileage)]

[1] 1017936

In [30]:
# Apply functions on multiple columns

df[,.(Max_mileage = max(mileage),
      Min_mileage = min(mileage),
      Std_mileage = sd(mileage))]

  Max_mileage Min_mileage Std_mileage
1 1017936     0           59705.52

In [31]:
# Maximum mileage by year

df[, max(mileage),by = year]

   year V1
1  2008  325611
2  2011  309564
3  2018   93350
4  2014  363810
5  2010 1017936
6  2017  209915
7  2009  982486
8  2013  999999
9  2015  205796
10 2020   23984
11 2016  147935
12 1973   46226
13 2003  507985
14 2019   73552
15 2002  214800
16 2000  231240
17 2001  295780
18 2005  225236
19 2012  902041
20 2006  268040
21 2007  267834
22 1998  300021
23 2004  308451
24 1994  206162
25 1997  203297
26 1996  296860
27 1999  226972
28 1984   41577
29 1995  274706
30 1993       0

In [32]:
# Count by model and year

df[,.(Count = .N), 
   by = .(model, year)]

    model       year Count
1   cruiser     2008   1
2   se          2011   1
3   mpv         2018  11
4   door        2014  71
5   1500        2018   9
6   pk          2010   2
7   door        2017 156
8   malibu      2018   6
9   mpv         2017  35
10  coupe       2009   1
11  wagon       2017   4
12  door        2013  73
13  forte       2018   2
14  encore      2018   1
15  door        2015 101
16  sorento     2020   1
17  doors       2017  15
18  chassis     2008   2
19  q70         2016   1
20  camaro      1973   1
21  convertible 2003   1
22  vans        2016   2
23  pk          2003   1
24  srw         2017   4
25  compass     2019   6
26  malibu      2017   2
27  enclave     2017   1
28  300         2019   5
29  cherokee    2019   3
30  pacifica    2020   1
... ...         ...  ...
325 armada      2017  1
326 altima      2018  6
327 rogue       2018 22
328 pathfinder  2018 13
329 rogue       2017  5
330 versa       2018 25
331 altima      2019 12
332 titan       2017  3
333 sedan       2018  3
334 frontier    2018  3
335 sedan       2017  1
336 juke        2017  1
337 armada      2020  1
338 pathfinder  2017  2
339 sentra      2017  3
340 armada      2019  1
341 rogue       2020  9
342 cargo       2020  1
343 murano      2016  2
344 armada      2018  1
345 maxima      2018  2
346 xterra      2012  1
347 murano      2018  3
348 titan       2018  1
349 kicks       2019  1
350 pathfinder  2019  7
351 xd          2017  1
352 rogue       2016  5
353 nvp         2016  1
354 titan       2019  1

In [33]:
# Call & Apply functions for grouping

df[,.(Count = .N), 
   by = .(Lessthan2005 = 
             year < 2005)]

  Lessthan2005 Count
1 FALSE        2458
2  TRUE          41

In [34]:
# Do the analysis on selected rows only

df[1:15,.(Max_mileage =
      max(mileage),
      Min_mileage =
      min(mileage),
      Std_mileage =
      sd(mileage))]

  Max_mileage Min_mileage Std_mileage
1 274117      6654        75934.62

In [35]:
# Remove a column

head(df[, brand := NULL])

  V1 price model   year title_status  mileage color  vin
1 0   6300 cruiser 2008 clean vehicle 274117  black  jtezu11f88k007763
2 1   2899 se      2011 clean vehicle 190552  silver 2fmdk3gc4bbb02217
3 2   5350 mpv     2018 clean vehicle  39590  silver 3c4pdcgg5jt346413
4 3  25000 door    2014 clean vehicle  64146  blue   1ftfw1et4efc23745
5 4  27700 1500    2018 clean vehicle   6654  red    3gcpcrec2jg473991
6 5   5700 mpv     2018 clean vehicle  45561  white  2c4rdgeg9jr237989
  lot       state      country condition
1 159348797 new jersey usa     10 days left
2 166951262 tennessee  usa     6 days left
3 167655728 georgia    usa     2 days left
4 167753855 virginia   usa     22 hours left
5 167763266 florida    usa     22 hours left
6 167655771 texas      usa     2 days left

In [36]:
# Return the first occurance where title_status is clean vehicle

setkey(df, title_status)
df["clean vehicle", mult = "first"]

  V1 price model   year title_status  mileage color vin               lot
1 0  6300  cruiser 2008 clean vehicle 274117  black jtezu11f88k007763 159348797
  state      country condition
1 new jersey usa     10 days left

In [37]:
# Return the last occurance where title_status is clean vehicle

setkey(df, title_status)
df["clean vehicle", mult = "last"]

  V1   price model year title_status  mileage color  vin
1 2498 9200  versa 2018 clean vehicle 31371   silver 3n1cn7ap4jl884311
  lot       state   country condition
1 167762228 florida usa     21 hours left

In [38]:
# Return a count for year in (2018 or 2015) and country usa

setkey(df, year, country)

df[.(c(2018,2015), "usa"), .N]

[1] 590

In [39]:
# Return the splitted count for year in (2018 or 2015) and country usa
setkey(df, year, country)
df[.(c(2018,2015),  
      "usa"), .N,
   by =.EACHI]

  year country N
1 2018 usa     394
2 2015 usa     196

In [43]:
# Order in ascending order

tail(df[order(year)])

  V1   price model  year title_status      mileage color  vin
1 2339 19800 rogue  2020 clean vehicle     14850   silver knmat2mv2lp511637
2 2341 18000 rogue  2020 clean vehicle     12748   black  jn8at2mt4lw003761
3 2342 19800 rogue  2020 clean vehicle     14531   blue   jn8at2mv1lw104855
4 2343 19700 rogue  2020 clean vehicle     15931   black  knmat2mv1lp508342
5 2344 20100 rogue  2020 clean vehicle     10875   blue   jn8at2mvxlw103235
6  206    25 vehicl 2020 salvage insurance  7232   black  2gnaxkev6l6128374
  lot       state     country condition
1 167614830 minnesota usa     14 hours left
2 167614833 minnesota usa     14 hours left
3 167614835 minnesota usa     14 hours left
4 167614836 minnesota usa     14 hours left
5 167614842 minnesota usa     14 hours left
6 167756877 kentucky  usa     3 days left

In [44]:
# Order in descending order

tail(setorder(df, -year))

  V1  price model   year title_status      mileage color      vin
1 410     0 door    1995 salvage insurance 274706  green      2gcec19h8s1195266
2 322     0 chassis 1994 salvage insurance      0  green      1fdee14n7rha47894
3 362    25 pickup  1994 salvage insurance 206162  white      1ftdf15y2rnb12612
4 545     0 door    1993 salvage insurance      0  light blue 1gkfk16k5pj701631
5 405    25 door    1984 salvage insurance  41577  white      2ftcf15y9eca14589
6  32 29800 camaro  1973 clean vehicle      46226  red        1q87t3n166389
  lot       state        country condition
1 167425634 arizona      usa     2 days left
2 167359174 california   usa     19 hours left
3 167361489 georgia      usa     2 days left
4 167358601 colorado     usa     18 hours left
5 167611661 arkansas     usa     17 hours left
6 167763370 pennsylvania usa     22 hours left

In [45]:
# "year" in descending and "mileage" in ascending

tail(setorder(df, -year, mileage))

  V1  price model   year title_status      mileage color      vin
1 410     0 door    1995 salvage insurance 274706  green      2gcec19h8s1195266
2 322     0 chassis 1994 salvage insurance      0  green      1fdee14n7rha47894
3 362    25 pickup  1994 salvage insurance 206162  white      1ftdf15y2rnb12612
4 545     0 door    1993 salvage insurance      0  light blue 1gkfk16k5pj701631
5 405    25 door    1984 salvage insurance  41577  white      2ftcf15y9eca14589
6  32 29800 camaro  1973 clean vehicle      46226  red        1q87t3n166389
  lot       state        country condition
1 167425634 arizona      usa     2 days left
2 167359174 california   usa     19 hours left
3 167361489 georgia      usa     2 days left
4 167358601 colorado     usa     18 hours left
5 167611661 arkansas     usa     17 hours left
6 167763370 pennsylvania usa     22 hours left

In [46]:
# Rename columns
setnames(df,c("year","mileage"),c("YEAR", "MILEAGE"))
tail(df)

  V1  price model   YEAR title_status      MILEAGE color      vin
1 410     0 door    1995 salvage insurance 274706  green      2gcec19h8s1195266
2 322     0 chassis 1994 salvage insurance      0  green      1fdee14n7rha47894
3 362    25 pickup  1994 salvage insurance 206162  white      1ftdf15y2rnb12612
4 545     0 door    1993 salvage insurance      0  light blue 1gkfk16k5pj701631
5 405    25 door    1984 salvage insurance  41577  white      2ftcf15y9eca14589
6  32 29800 camaro  1973 clean vehicle      46226  red        1q87t3n166389
  lot       state        country condition
1 167425634 arizona      usa     2 days left
2 167359174 california   usa     19 hours left
3 167361489 georgia      usa     2 days left
4 167358601 colorado     usa     18 hours left
5 167611661 arkansas     usa     17 hours left
6 167763370 pennsylvania usa     22 hours left

In [48]:
# Unique rows

unique(df[,.(color,state)])

    color      state
1   black      virginia
2   white      pennsylvania
3   gray       california
4   black      california
5   blue       ohio
6   gray       virginia
7   gray       pennsylvania
8   no_color   south carolina
9   no_color   ohio
10  gray       michigan
11  white      ohio
12  orange     pennsylvania
13  silver     missouri
14  silver     california
15  black      kentucky
16  silver     florida
17  black      pennsylvania
18  gray       arizona
19  blue       minnesota
20  white      california
21  blue       north carolina
22  white      illinois
23  red        virginia
24  black      minnesota
25  white      georgia
26  gray       georgia
27  green      georgia
28  silver     indiana
29  silver     minnesota
30  black      nevada
... ...        ...
313 color:     new jersey
314 color:     california
315 gold       florida
316 white      utah
317 green      texas
318 orange     oklahoma
319 black      utah
320 white      maryland
321 orange     georgia
322 burgundy   oklahoma
323 silver     kansas
324 orange     north carolina
325 white      arkansas
326 color:     georgia
327 yellow     minnesota
328 orange     utah
329 yellow     illinois
330 dark blue  minnesota
331 brown      mississippi
332 green      minnesota
333 maroon     wyoming
334 red        maryland
335 gold       kansas
336 green      maryland
337 gold       arkansas
338 gray       utah
339 brown      arkansas
340 green      california
341 green      arizona
342 light blue colorado

In [49]:
# Create new column

z = df[, country_state := paste(country, state)][,.(country_state, country, state)]

head(z)

  country_state    country state
1 usa virginia     usa     virginia
2 usa pennsylvania usa     pennsylvania
3 usa california   usa     california
4 usa california   usa     california
5 usa ohio         usa     ohio
6 usa virginia     usa     virginia